(() => {
  'use strict';
  if (window.__V20_CONSENSUS_OVERLAY__) return;
  window.__V20_CONSENSUS_OVERLAY__ = true;
  const overlay={data:null,starting:false,filter:'ALL',observer:null,dossierObserver:null,scheduled:false};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
  const num=(v,d=2)=>finite(v)?Number(v).toLocaleString('ar-EG',{maximumFractionDigits:d}):'—';
  const pct=v=>finite(v)?`${num(v,1)}%`:'—';
  const yesNo=v=>v===true?'<span class="consensus-yes">نعم</span>':'<span class="consensus-no">لا</span>';
  async function load(){const r=await fetch('../data/v20/cross-version-consensus.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d.schemaVersion!=='20.0.0-cross-version-consensus-1')throw new Error('Consensus schema mismatch');if(d.scoreDefinition?.independentModelCount!==2||d.scoreDefinition?.historicalPerformanceUsedInScore!==false)throw new Error('Consensus score contract drift');if(d.governance?.displayPriorityOnly!==true||d.governance?.changesFinalDecision!==false||d.governance?.changesExecutionPermission!==false||d.governance?.changesMainAppMethodology!==false||d.governance?.v17RemainsProductionAuthority!==true)throw new Error('Consensus governance drift');return d;}
  function rowMap(){return new Map((overlay.data?.current?.rows||[]).map(r=>[String(r.ticker||'').toUpperCase(),r]));}
  function badge(r){if(!r)return '<span class="consensus-badge consensus-badge-none">0/2</span>';if(r.consensusScore===100)return '<span class="consensus-badge consensus-badge-full" title="اتفاق MAIN APP وV19">2/2 · 100</span>';if(r.consensusScore===50)return '<span class="consensus-badge consensus-badge-single" title="اختيار محرك مستقل واحد">1/2 · 50</span>';return '<span class="consensus-badge consensus-badge-none">0/2</span>';}
  function mountSummary(){const board=document.getElementById('decisionBoardPanel');if(!board||document.getElementById('consensusOverlayPanel'))return;const d=overlay.data,shared=d.current?.sharedTickers||[],hist=d.historicalEvidence?.v16V19Consensus||{},delta=d.historicalEvidence?.deltaConsensusVsV16Only||{};const p=document.createElement('section');p.id='consensusOverlayPanel';p.className=`consensus-overlay-panel ${d.current?.fullMainAppBasketAgreement?'is-full-consensus':''}`;p.dataset.executionAuthority='none';p.innerHTML=`<div class="consensus-overlay-head"><div><span class="eyebrow">طبقة اتفاق مستقلة · Display Priority Only</span><h3>Cross-Version Consensus</h3><p>يرفع أولوية العرض عندما يتفق MAIN APP وV19 في نفس الجلسة. لا يغيّر Final Decision ولا Execution Permission ولا خوارزمية أي إصدار.</p></div><span class="consensus-score-hero">${num(d.current?.sharedCount,0)}/${num(d.current?.mainAppBasketSize,0)} اتفاق حالي</span></div><div class="consensus-current-strip"><div><span>جلسة الاتفاق</span><strong>${esc(d.sessionDate||'غير متزامنة')}</strong><small>${d.current?.sessionAligned?'MAIN APP وV19 على نفس Session':'Fail Closed — لا يتم احتساب Consensus'}</small></div><div><span>MAIN APP Agreement</span><strong>${pct(d.current?.mainAppAgreementRatePct)}</strong><small>${d.current?.fullMainAppBasketAgreement?'تطابق كامل للسلة الرئيسية':'تطابق جزئي'}</small></div><div><span>Historical Avg Close</span><strong>${pct(hist.avgNextCloseGrossPct)}</strong><small>اتفاق V16.9 × V19 · ${num(hist.selections,0)} اختيارًا تاريخيًا</small></div><div><span>Conservative Target Hit</span><strong>${pct(hist.conservativeTargetHitRateOfExecutablePct)}</strong><small>ميزة مقابل V16-only: ${finite(delta.conservativeTargetRateOfExecutablePp)?`${num(delta.conservativeTargetRateOfExecutablePp,2)} نقطة`:'—'}</small></div></div><div class="consensus-current-list">${shared.length?shared.map(t=>`<span class="consensus-current-chip" data-consensus-symbol="${esc(t)}"><b>${esc(t)}</b><small>2/2 · Score 100</small></span>`).join(''):'<span class="consensus-empty">لا يوجد اتفاق 2/2 في الجلسة الحالية.</span>'}</div><div class="consensus-governance-note"><b>الحوكمة:</b> Consensus Score = عدد الأصوات المستقلة ÷ 2 × 100. الأداء التاريخي Evidence فقط ولا يدخل في المعادلة. V17 يظل سلطة الأهلية والتنفيذ الوحيدة.</div>`;const notice=board.querySelector('.decision-board-notice');if(notice)notice.insertAdjacentElement('afterend',p);else board.prepend(p);const filters=board.querySelector('.decision-filters');if(filters&&!document.getElementById('consensusFilter')){const label=document.createElement('label');label.innerHTML=`Consensus<select id="consensusFilter"><option value="ALL">كل الأسهم</option><option value="FULL">2/2 فقط</option><option value="SINGLE">1/2 فقط</option><option value="NONE">بدون اتفاق</option></select>`;filters.appendChild(label);label.querySelector('select').addEventListener('change',e=>{overlay.filter=e.target.value;scheduleApply();});}}
  function shouldShow(score){if(overlay.filter==='ALL')return true;if(overlay.filter==='FULL')return score===100;if(overlay.filter==='SINGLE')return score===50;return score===0;}
  function decorateTable(){const map=rowMap(),tbody=document.getElementById('decisionRows');if(!tbody)return;const rows=[...tbody.querySelectorAll('tr[data-symbol]')];rows.forEach((el,index)=>{const symbol=String(el.dataset.symbol||'').toUpperCase(),c=map.get(symbol)||null,score=c?.consensusScore||0;el.dataset.consensusScore=String(score);el.dataset.consensusOriginalIndex=el.dataset.consensusOriginalIndex||String(index);el.classList.toggle('consensus-priority-row',score===100);el.hidden=!shouldShow(score);const cell=el.querySelector('.decision-symbol');if(cell&&!cell.querySelector('.consensus-badge'))cell.insertAdjacentHTML('beforeend',badge(c));});const ordered=rows.slice().sort((a,b)=>{const as=Number(a.dataset.consensusScore||0)===100?1:0,bs=Number(b.dataset.consensusScore||0)===100?1:0;if(as!==bs)return bs-as;return Number(a.dataset.consensusOriginalIndex||0)-Number(b.dataset.consensusOriginalIndex||0);});if(ordered.some((el,i)=>tbody.children[i]!==el))ordered.forEach(el=>tbody.appendChild(el));}
  function decorateCards(){const map=rowMap(),holder=document.getElementById('decisionCards');if(!holder)return;const cards=[...holder.querySelectorAll('[data-symbol]')];cards.forEach((el,index)=>{const symbol=String(el.dataset.symbol||'').toUpperCase(),c=map.get(symbol)||null,score=c?.consensusScore||0;el.dataset.consensusScore=String(score);el.dataset.consensusOriginalIndex=el.dataset.consensusOriginalIndex||String(index);el.classList.toggle('consensus-priority-card',score===100);el.hidden=!shouldShow(score);const top=el.querySelector('.decision-card-top > div');if(top&&!top.querySelector('.consensus-badge'))top.insertAdjacentHTML('beforeend',badge(c));});const ordered=cards.slice().sort((a,b)=>{const as=Number(a.dataset.consensusScore||0)===100?1:0,bs=Number(b.dataset.consensusScore||0)===100?1:0;if(as!==bs)return bs-as;return Number(a.dataset.consensusOriginalIndex||0)-Number(b.dataset.consensusOriginalIndex||0);});if(ordered.some((el,i)=>holder.children[i]!==el))ordered.forEach(el=>holder.appendChild(el));}
  function augmentDossier(){const body=document.getElementById('decisionDossierBody');if(!body||body.querySelector('[data-consensus-dossier]'))return;const h2=body.querySelector('.decision-dossier-head h2');if(!h2)return;const symbol=String(h2.textContent||'').split('—')[0].trim().split(/\s+/)[0].toUpperCase(),c=rowMap().get(symbol);if(!c)return;const hist=c.historicalConsensusEvidence,s=document.createElement('section');s.className='decision-dossier-section consensus-dossier-section';s.dataset.consensusDossier='true';s.innerHTML=`<h3>Cross-Version Consensus — أولوية عرض فقط</h3><div class="decision-kv"><span>Consensus Score</span><strong>${num(c.consensusScore,0)} / 100</strong><span>الأصوات المستقلة</span><strong>${num(c.independentVotes,0)} / ${num(c.independentModelCount,0)}</strong><span>MAIN APP</span><strong>${yesNo(c.mainAppSelected)}</strong><span>V19</span><strong>${yesNo(c.v19Selected)}</strong><span>V20 Native Discovery</span><strong>${yesNo(c.v20NativeDiscovered)}</strong><span>مرات الاتفاق التاريخية</span><strong>${hist?num(hist.occurrences,0):'—'}</strong><span>Target rate تاريخيًا</span><strong>${hist?pct(hist.rawMarketTargetRatePct):'—'}</strong><span>متوسط العائد التاريخي</span><strong>${hist?pct(hist.avgNextCloseGrossPct):'—'}</strong><span>متوسط أقصى صعود</span><strong>${hist?pct(hist.avgMaxUpsideFromEntryHighPct):'—'}</strong></div><div class="decision-no-confidence"><b>لا يساوي توصية تنفيذ.</b> Consensus لا يفتح V17 Global Gate ولا يغيّر Final Decision أو Stop/Target أو أوزان MAIN APP.</div>`;body.querySelector('.decision-dossier-grid')?.appendChild(s);}
  function applyAll(){overlay.scheduled=false;if(!overlay.data)return;decorateTable();decorateCards();augmentDossier();}
  function scheduleApply(){if(overlay.scheduled)return;overlay.scheduled=true;requestAnimationFrame(applyAll);}
  function observe(){const content=document.getElementById('decisionContent'),dossier=document.getElementById('decisionDossierBody');if(content&&!overlay.observer){overlay.observer=new MutationObserver(scheduleApply);overlay.observer.observe(content,{childList:true,subtree:true});}if(dossier&&!overlay.dossierObserver){overlay.dossierObserver=new MutationObserver(scheduleApply);overlay.dossierObserver.observe(dossier,{childList:true,subtree:true});}}
  async function init(){if(overlay.data||overlay.starting)return;overlay.starting=true;try{overlay.data=await load();mountSummary();applyAll();observe();document.dispatchEvent(new CustomEvent('v20:consensus-overlay-ready',{detail:{sessionDate:overlay.data.sessionDate,sharedTickers:overlay.data.current?.sharedTickers||[],fullAgreement:overlay.data.current?.fullMainAppBasketAgreement===true}}));}catch(e){const board=document.getElementById('decisionBoardPanel');if(board&&!document.getElementById('consensusOverlayError')){const box=document.createElement('div');box.id='consensusOverlayError';box.className='consensus-overlay-error';box.textContent=`Consensus Overlay غير متاح: ${e.message}`;board.querySelector('.decision-board-notice')?.insertAdjacentElement('afterend',box);}}finally{overlay.starting=false;}}
  document.addEventListener('v20:decision-board-ready',init,{once:true});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
})();
