(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const numeric=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
  const num=(v,d=2)=>numeric(v)===null?'—':numeric(v).toLocaleString('ar-EG',{maximumFractionDigits:d});
  const pct=v=>numeric(v)===null?'—':`${num(v,3)}%`;
  const load=async(url,optional=false)=>{try{const r=await fetch(url,{cache:'no-store'});if(!r.ok){if(optional)return null;throw new Error(`${url}: HTTP ${r.status}`)}return r.json()}catch(e){if(optional)return null;throw e}};
  const rowsOf=doc=>Array.isArray(doc?.rows)?doc.rows:Object.entries(doc?.rows||{}).map(([symbol,row])=>({symbol,...(row||{})}));
  const mapOf=doc=>new Map(rowsOf(doc).filter(x=>x?.symbol).map(x=>[x.symbol,x]));
  const roleAr=r=>({MISSING:'ناقص',STALE:'قديم',CONFLICT:'تعارض حرج'}[r]||r);
  const observedAr=c=>({OBSERVED_CURRENT_CRITICAL_SOURCE_CONFLICT:'تعارض مصدر حرج قائم حاليًا',OBSERVED_TRUSTED_SR_ROW_STALE:'صف S/R موثوق لكنه قديم عن الجلسة المرجعية',OBSERVED_V17_HISTORY50_SYMBOL_MISSING:'لا يوجد سجل للرمز داخل history-50 المرجعي',OBSERVED_V17_HISTORY50_CURRENT_SESSION_ROW_MISSING:'history-50 لا يحتوي صف الجلسة الحالية',OBSERVED_V17_HISTORY50_CURRENT_OHLC_INVALID:'صف الجلسة الحالية في history-50 غير صالح كـOHLC',OBSERVED_V17_HISTORY50_CURRENT_ROW_NOT_SOURCE_SESSION_VERIFIED:'صف الجلسة موجود لكن sourceSessionVerified غير مثبت',OBSERVED_INTERNAL_SR_ROW_MISSING:'مدخل history-50 موجود لكن صف Internal S/R غير موجود',OBSERVED_AGGREGATE_MISSING_REQUIRES_V17_REBUILD_REVIEW:'الحالة تحتاج مراجعة وإعادة بناء V17 لتحديد سبب الاستبعاد النهائي'}[c]||c||'—');
  const supState=s=>({ELIGIBLE_FOR_V17_REVIEW:'صالح للمراجعة داخل V17 — ليس تنفيذًا',SUPPLEMENTAL_EVIDENCE_INCOMPLETE:'دليل إضافي غير مكتمل',UNAVAILABLE:'غير متاح'}[s]||s||'—');
  const startaState=s=>({CURRENT_REVIEW_CANDIDATE:'Current review candidate — supplemental فقط',SUPPLEMENTAL_EVIDENCE_INCOMPLETE:'دليل Starta غير مكتمل',FETCH_FAILED:'فشل جلب Starta',SYMBOL_MAP_ENTRY_MISSING:'هوية الرمز غير متاحة'}[s]||s||'—');
  const reviewStateAr=s=>({CRITICAL_SOURCE_CONFLICT_MANUAL_REVIEW:'مراجعة يدوية عاجلة لتعارض مصدر حرج',AUTHORITATIVE_OHLC_REPAIR_REQUIRED:'إصلاح OHLC المرجعية مطلوب',ALTERNATE_PROVIDER_REQUIRED:'مصدر بديل مطلوب للمراجعة',PROVIDER_IDENTITY_REFERENCE_CONFLICT_REVIEW:'مراجعة تعارض سعر هوية المصدر',CURRENT_SESSION_EVIDENCE_REQUIRED:'دليل جلسة حالية مطلوب',PRICE_REFERENCE_RECONCILIATION_REQUIRED:'مطابقة السعر/المرجع مطلوبة',SUPPLEMENTAL_CANDIDATE_CLEAN_FOR_MANUAL_V17_REVIEW:'مرشح إضافي نظيف للمراجعة اليدوية',V17_PROVENANCE_REVIEW_REQUIRED:'إعادة تحقق provenance داخل V17 مطلوبة'}[s]||s||'—');
  const handoffStateAr=s=>({CRITICAL_SOURCE_CONFLICT_REMAINS:'التعارض الحرج ما زال قائمًا — لا اختيار تلقائي للمصدر',AUTHORITATIVE_OHLC_REPAIR_REQUIRED:'إصلاح OHLC المرجعية مطلوب قبل إعادة البناء',STARTA_CURRENT_RECONCILED_SR_REFRESH_REVIEW:'Starta حالية ومتطابقة سعريًا — مراجعة تحديث S/R داخل V17',STARTA_CURRENT_RECONCILED_HISTORY50_REVIEW_REQUIRED:'Starta حالية ومتطابقة سعريًا — مراجعة history-50/provenance مطلوبة',STARTA_CURRENT_MARKET_REFERENCE_MISSING:'Starta حالية لكن مرجع السوق الموثق غير متاح',NO_CURRENT_STARTA_SESSION:'Starta لا تصل للجلسة الحالية',MANUAL_AUTHORITATIVE_REVIEW_REQUIRED:'مراجعة authoritative يدوية مطلوبة'}[s]||s||'—');
  const blockerAr=c=>({V17_CANDIDATE_EVIDENCE_MISSING:'الرمز ما زال ضمن missing set في V17',V17_HISTORY50_CURRENT_ROW_NOT_SOURCE_SESSION_VERIFIED:'صف history-50 الحالي غير موثق source-session',V17_HISTORY50_CURRENT_SESSION_ROW_MISSING:'صف الجلسة الحالية غير موجود في history-50',V17_HISTORY50_CURRENT_OHLC_INVALID:'OHLC المرجعية الحالية غير صالحة',V17_INTERNAL_SR_STALE:'Internal S/R قديم عن الجلسة',V17_CRITICAL_SOURCE_CONFLICT:'تعارض مصدر حرج ما زال قائمًا',SUPPLEMENTAL_PROVIDER_FETCH_FAILED:'فشل جلب المصدر الإضافي',SUPPLEMENTAL_SYMBOL_MAP_ENTRY_MISSING:'هوية الرمز غير موجودة في symbol-map',SUPPLEMENTAL_IDENTITY_UNVERIFIED:'هوية المصدر الإضافي غير متحققة',SUPPLEMENTAL_CURRENT_SESSION_MISSING:'المصدر الإضافي لا يصل للجلسة الحالية',SUPPLEMENTAL_CURRENT_OHLC_INVALID:'OHLC الإضافية الحالية غير صالحة',SUPPLEMENTAL_PRICE_NOT_RECONCILED:'السعر الإضافي غير متصالح مع المرجع الحالي',SUPPLEMENTAL_IDENTITY_REFERENCE_PRICE_CONFLICT:'Metadata سعر هوية المصدر تختلف بشدة عن المرجع'}[c]||c);
  const actionAr=c=>({REVERIFY_HISTORY50_CURRENT_SESSION_PROVENANCE:'إعادة توثيق provenance لصف history-50 الحالي',ACQUIRE_AUTHORITATIVE_CURRENT_SESSION_OHLC:'الحصول على OHLC حالية من مصدر مقبول',REPAIR_AUTHORITATIVE_CURRENT_SESSION_OHLC:'إصلاح OHLC المرجعية بدون توليد صناعي',REBUILD_CURRENT_SESSION_INTERNAL_SR:'إعادة بناء Internal S/R بعد توثيق المدخل',DOCUMENT_AND_RESOLVE_SOURCE_CONFLICT:'توثيق ومراجعة تعارض المصادر داخل V17',TRY_ACCEPTED_ALTERNATE_PROVIDER:'تجربة مصدر بديل كدليل مراجعة فقط',VERIFY_SUPPLEMENTAL_IDENTITY:'التحقق من هوية المصدر الإضافي',ACQUIRE_CURRENT_SESSION_FROM_ALTERNATE_PROVIDER:'الحصول على جلسة حالية من مصدر بديل',REJECT_INVALID_SUPPLEMENTAL_OHLC:'رفض OHLC إضافية غير صالحة',VERIFY_PRICE_SCALE_AND_REFERENCE:'مراجعة scale/reference بدون افتراض corporate action',RECONCILE_PROVIDER_IDENTITY_PRICE_REFERENCE:'مطابقة metadata سعر هوية المصدر مع المرجع'}[c]||c);
  function badge(role){return `<span class="role role-${esc(String(role).toLowerCase())}">${esc(roleAr(role))}</span>`}
  function sourceBlock(title,kind,items){return `<section class="source-box ${kind}"><div class="source-title"><b>${esc(title)}</b></div><div class="source-facts">${items.map(([label,value,sub])=>`<div><span>${esc(label)}</span><strong>${esc(value??'—')}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`).join('')}</div></section>`}
  function reviewPacketBlock(review){if(!review)return'';const blockers=review.blockers||[],actions=review.reviewActions||[],identity=review.providerIdentityReference||{};return `<section class="review-packet ${review.reviewPriority==='HIGH'?'review-high':''}"><div class="review-packet-head"><div><span>Manual review packet</span><strong>${esc(reviewStateAr(review.reviewState))}</strong></div><b>${esc(review.reviewPriority||'—')}</b></div><div class="review-columns"><div><span class="review-label">Blocking checks</span>${blockers.length?blockers.map(x=>`<div class="review-item blocker-${esc(String(x.severity||'').toLowerCase())}"><b>${esc(blockerAr(x.code))}</b><small>${esc(x.detail||'')}</small></div>`).join(''):'<div class="review-item"><b>لا توجد blockers إضافية</b></div>'}</div><div><span class="review-label">Manual actions</span>${actions.length?actions.map(x=>`<div class="review-item"><b>${esc(actionAr(x.code))}</b><small>${esc(x.detail||'')}</small></div>`).join(''):'<div class="review-item"><b>لا يوجد إجراء إضافي مسجل</b></div>'}</div></div>${identity.conflict?`<div class="identity-alert"><strong>Provider identity/reference anomaly</strong><span>difference ${pct(identity.localDifferencePct)} • adapter diagnostic guard ${pct(identity.diagnosticGuardPct)} • guarded execution policy = ${identity.guardedPolicyRequested?'ON':'OFF'}</span><small>هذا Diagnostic للمراجعة فقط، وليس threshold تنفيذ جديدًا.</small></div>`:''}<div class="review-safety"><b>Clean supplemental candidate: ${review.cleanSupplementalCandidate?'YES':'NO'}</b><span>V17 trusted = NO • Execution eligible = NO • Auto-resolution = NO</span></div></section>`}
  function handoffBlock(h){if(!h)return'';const m=h.evidenceMatrix||{},d=h.deltasPct||{},s=m.startaHistory||{},y=m.yahooHistory||{},hm=m.history50||{},mr=m.marketReference||{};const matrix=[['Market ref',num(mr.price,4),'V20 current'],['history-50',num(hm.close,4),hm.currentSessionRowPresent?'current row':'no current row'],['Yahoo history',num(y.close,4),y.currentSession?'current':'not current'],['Yahoo metadata',num(m.yahooIdentity?.regularMarketPrice,4),'identity metadata'],['Starta history',num(s.close,4),s.currentSession?'current':'not current'],['Starta metadata',num(m.startaIdentity?.lastPrice,4),'identity metadata']];const deltas=[['Market ↔ H50',pct(d.marketVsHistory50)],['Market ↔ Yahoo hist',pct(d.marketVsYahooHistory)],['Market ↔ Starta',pct(d.marketVsStartaHistory)],['H50 ↔ Starta',pct(d.history50VsStartaHistory)],['Yahoo ↔ Starta',pct(d.yahooHistoryVsStartaHistory)]];return `<section class="handoff-block" data-handoff-state="${esc(h.triangulationState)}"><div class="handoff-head"><div><span>V17 handoff verdict</span><strong>${esc(handoffStateAr(h.triangulationState))}</strong></div><b>MANUAL ONLY</b></div><div class="price-matrix">${matrix.map(([a,b,c])=>`<div><span>${esc(a)}</span><strong>${esc(b)}</strong><small>${esc(c)}</small></div>`).join('')}</div><div class="delta-row">${deltas.map(([a,b])=>`<span><b>${esc(a)}</b> ${esc(b)}</span>`).join('')}</div><div class="handoff-action"><b>Authoritative review action</b><span>${esc(h.authoritativeReviewAction||'Manual V17 review required.')}</span></div><div class="handoff-safety"><strong>Auto-repair = NO • Auto-trust = NO • Execution effect = NO</strong><small>Supplemental consensus is not authority. History continuity rejection blocks automatic repair.</small></div></section>`}
  function card(row,review,starta,handoff){
    const roles=row.remediationRoles||[],h=row.authoritativeV17?.history50||{},sr=row.authoritativeV17?.internalSr||{},sup=row.supplementalCandidate||{},conf=row.authoritativeV17?.conflict||null,ready=sup.eligibleForV17Review===true;
    const authBlock=sourceBlock('V17 authoritative input','authoritative',[
      ['المسار',h.inputPath||'data/history-50.json',`rows ${h.rowCount??0} • valid OHLC ${h.validOhlcCount??0}`],['آخر جلسة',h.latestSession||'—',h.currentSessionRowPresent?'صف الجلسة الحالية موجود':'صف الجلسة الحالية غير موجود'],['Current OHLC',h.currentSessionOhlcValid?'صالح':'غير صالح/غير متاح',h.currentSessionSource||'—'],['Source session',h.currentSessionSourceVerified?'Verified':'غير مثبت',h.currentSessionSourceQuality||h.marketSource||'—'],['Internal S/R',sr.rowExists?(sr.sessionAligned?'صف حالي':'صف غير متزامن'):'لا يوجد صف',`trusted=${sr.trustedForExecution===true?'yes':'no'} • eligible=${sr.executionEligible===true?'yes':'no'}`],['Conflict',conf?`${conf.source||'—'} • ${pct(conf.maxDiffPct)}`:'لا يوجد على هذا target',conf?.state||'—']]);
    const identity=sup.identityEvidence||{};
    const yahooBlock=sourceBlock('Yahoo supplemental review candidate','supplemental',[
      ['الحالة',supState(sup.status),`fetch ${row.acquisitionAttempt?.status||'—'}`],['Identity',sup.identityVerified?'Verified':'غير متحقق',`score ${num(sup.identityScore,0)} • metadata diff ${pct(identity.localDifferencePct)}`],['آخر جلسة',sup.latestSession||'—',`accepted rows ${sup.acceptedRowCount??0}`],['Current OHLC',sup.currentSessionOhlc?.valid?'صالح':'غير متاح/غير صالح',sup.currentSessionOhlc?`O ${num(sup.currentSessionOhlc.open,4)} H ${num(sup.currentSessionOhlc.high,4)} L ${num(sup.currentSessionOhlc.low,4)} C ${num(sup.currentSessionOhlc.close,4)}`:'—'],['Price reconcile',sup.priceReconciled?'متطابق ضمن الحد':'غير متطابق/غير متاح',`diff ${pct(sup.currentPriceDifferencePct)} • limit ${pct(sup.priceTolerancePct)}`],['V17 trust','NO',`executionEligible=false • future rejected ${sup.futureRowsRejected??0}`]]);
    const st=starta||{};const exact=st.historyContinuity?.exact||{};
    const startaBlock=sourceBlock('Starta secondary triangulation','starta',[
      ['الحالة',startaState(st.status),`source role ${st.sourceRole||'—'}`],['Identity',st.identityVerified?'Verified':'غير متحقق',`${st.identity?.providerNameEn||'—'} • ${st.identity?.providerIsin||'—'}`],['آخر جلسة',st.latestSession||'—',`accepted rows ${st.acceptedRowCount??0}`],['Current OHLC',st.currentSessionOhlc?.valid?'صالح':'غير متاح/غير صالح',st.currentSessionOhlc?`O ${num(st.currentSessionOhlc.open,4)} H ${num(st.currentSessionOhlc.high,4)} L ${num(st.currentSessionOhlc.low,4)} C ${num(st.currentSessionOhlc.close,4)}`:'—'],['Price reconcile',st.priceReconciled?'متطابق ضمن الحد':'غير متطابق/غير متاح',`diff ${pct(st.currentPriceDifferencePct)} • limit ${pct(st.priceTolerancePct)}`],['History continuity',st.historyContinuity?.accepted?'Accepted':'NOT accepted',`method ${st.historyContinuity?.method||'—'} • overlap ${exact.overlapCount??0} • matches ${exact.matches??0}`],['Yahoo ↔ Starta',st.yahooComparison?.status||'NOT_COMPARABLE',`close diff ${pct(st.yahooComparison?.closeDifferencePct)}`],['V17 trust','NO','executionEligible=false • auto-resolution=false']]);
    return `<article class="symbol-card ${review?.reviewPriority==='HIGH'?'critical-review':ready?'warn':'bad'}" data-role="${esc(roles.join(' '))}" data-review-ready="${ready?'true':'false'}" data-clean-supplemental="${review?.cleanSupplementalCandidate?'true':'false'}"><div class="symbol-head"><div><strong>${esc(row.symbol)}</strong><small>${roles.map(badge).join('')}</small></div><span class="review-state ${review?.cleanSupplementalCandidate?'review-clean':ready?'review-ready':'review-blocked'}">${handoff?esc(handoffStateAr(handoff.triangulationState)):review?esc(reviewStateAr(review.reviewState)):ready?'ELIGIBLE FOR V17 REVIEW':'REVIEW EVIDENCE INCOMPLETE'}</span></div><div class="observed"><b>Observed condition</b><span>${esc(observedAr(row.observedCondition||row.diagnosis))}</span><small>Cause verified: NO — لا يتم استنتاج split أو corporate action أو price-scale cause بدون دليل.</small></div><div class="source-grid">${authBlock}${yahooBlock}${startaBlock}</div>${reviewPacketBlock(review)}${handoffBlock(handoff)}<div class="guard"><strong>Review candidate only — لا يفتح التنفيذ تلقائيًا.</strong><span>Yahoo وStarta أدلة إضافية للمراجعة فقط؛ لا يصبح أي منهما V17 trusted evidence، ولا يغيّران Execution Grade أو أوزان الإنتاج.</span></div></article>`;
  }
  async function init(){try{
    const regression=await load('../data/v20/regression.json');
    const handoffSidecar=await load('../data/v20/sr-remediation-handoff.json',true);
    const audit=regression.supportResistanceRemediation||await load('../data/v20/sr-remediation-audit.json',true),packet=regression.supportResistanceReviewPacket||null,alt=regression.supportResistanceAlternateEvidence||null,handoffPrimary=regression.supportResistanceRemediationHandoff||null,handoff=rowsOf(handoffPrimary).length?handoffPrimary:handoffSidecar;
    if(!audit)throw new Error('S/R remediation evidence missing');if(audit.schemaVersion!=='20.0.0-sr-remediation-audit-3')throw new Error(`Unsupported remediation schema ${audit.schemaVersion||'missing'}`);if(packet&&packet.schemaVersion!=='20.0.0-sr-remediation-review-packet-1')throw new Error(`Unsupported review packet schema ${packet.schemaVersion}`);if(alt&&alt.schemaVersion!=='20.0.0-sr-remediation-alternate-evidence-1')throw new Error(`Unsupported Starta evidence schema ${alt.schemaVersion}`);if(!handoff)throw new Error('S/R remediation handoff evidence missing');if(handoff.schemaVersion!=='20.0.0-sr-remediation-handoff-1')throw new Error(`Unsupported handoff schema ${handoff.schemaVersion}`);
    const packetMap=mapOf(packet),altMap=mapOf(alt),handoffMap=mapOf(handoff),gap=audit.currentGap||{},summary=audit.summary||{},targets=audit.targets||audit.symbols||[];
    document.body.dataset.handoffSource=rowsOf(handoffPrimary).length?'regression':'sidecar';document.body.dataset.handoffCount=String(handoffMap.size);
    if(handoffMap.size===0)throw new Error('S/R remediation handoff rows missing');
    $('session').textContent=`جلسة ${audit.sessionDate||'—'}`;$('targetCount').textContent=String(summary.targetCount??targets.length);$('missingCount').textContent=String(summary.missingTargetCount??audit.missingSymbols?.length??0);$('roleSummary').textContent=`Missing ${summary.missingTargetCount??0} • Stale ${summary.staleTargetCount??0} • Conflict ${summary.conflictTargetCount??0}`;$('reviewReadyCount').textContent=String(packet?.summary?.cleanSupplementalCandidateCount??0);$('startaReadyCount').textContent=String(alt?.summary?.currentReviewCandidateCount??0);$('continuityAcceptedCount').textContent=String(alt?.summary?.historyContinuityAcceptedCount??0);
    if($('packetSummary'))$('packetSummary').innerHTML=packet?`<strong>Review queue:</strong> clean Yahoo supplemental ${packet.summary?.cleanSupplementalCandidateCount??0} • eligible-but-not-clean ${packet.summary?.supplementalEligibleButNotCleanCount??0} • identity conflicts ${packet.summary?.providerIdentityReferenceConflictCount??0} • alternate-provider required ${packet.summary?.alternateProviderRequiredCount??0}`:'Review packet not persisted yet.';
    if($('triangulationSummary'))$('triangulationSummary').innerHTML=alt&&handoff?`<strong>Starta triangulation:</strong> current candidates ${alt.summary?.currentReviewCandidateCount??0}/${alt.summary?.targetCount??0} • current session ${alt.summary?.currentSessionCount??0} • price reconciled ${alt.summary?.priceReconciledCount??0} • continuity accepted ${alt.summary?.historyContinuityAcceptedCount??0} • Yahoo+Starta both reconciled ${alt.summary?.bothSupplementalReconciledCount??0}. <strong>Handoff:</strong> ${Object.entries(handoff.summary?.stateCounts||{}).map(([k,v])=>`${esc(k)} ${v}`).join(' • ')}`:'Triangulation/handoff evidence not persisted yet.';
    $('coverageGap').textContent=`+${gap.trustedGap??0}`;$('coverageText').textContent=`${gap.trustedCount??0}/${gap.candidateUniverseCount??0} → مطلوب ${gap.requiredTrustedCount??'—'}`;$('freshGap').textContent=`+${gap.trustedFreshGap??0}`;$('freshText').textContent=`${gap.trustedFreshCount??0}/${gap.candidateUniverseCount??0} → مطلوب ${gap.requiredTrustedFreshCount??'—'}`;$('criticalGap').textContent=`+${gap.criticalGap??0}`;$('criticalText').textContent=`≈${gap.criticalEquivalent??0}/${gap.candidateUniverseCount??0} → مطلوب ${gap.requiredCriticalEquivalent??'—'}`;$('conflictGap').textContent=`${gap.sourceConflictCount??0}→0`;$('conflictText').textContent=(audit.conflictSymbols||[]).join('، ')||'لا يوجد';
    $('symbolCards').innerHTML=targets.length?targets.map(row=>card(row,packetMap.get(row.symbol),altMap.get(row.symbol),handoffMap.get(row.symbol))).join(''):'<div class="empty">لا توجد remediation targets في الـevidence الحالية.</div>';
    const conflictRows=targets.filter(x=>(x.remediationRoles||[]).includes('CONFLICT'));$('conflicts').innerHTML=conflictRows.length?conflictRows.map(x=>{const c=x.authoritativeV17?.conflict||{},h=handoffMap.get(x.symbol);return `<article class="conflict-card"><strong>${esc(x.symbol)}</strong><span>${esc(c.source||'—')} • ${esc(c.state||'—')}</span><small>maxDiff ${pct(c.maxDiffPct)} • ${h?esc(handoffStateAr(h.triangulationState)):'manual review'} • Auto-resolution = NO.</small></article>`}).join(''):'<div class="empty">لا توجد تعارضات حرجة ضمن targets الحالية.</div>';
    $('integrity').textContent=audit.inputIntegrity?.unchanged===true&&alt?.inputIntegrity?.unchanged!==false?'Protected V17/history-50 hashes unchanged':'Integrity check not confirmed';$('loading').classList.add('hidden');
  }catch(error){$('loading').classList.add('hidden');$('error').classList.remove('hidden');$('error').textContent=`تعذر تحميل Remediation Audit: ${error.message}`;}}
  init();
})();